{% set name = "res-mlp-pytorch" %}
{% set version = "0.0.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/res-mlp-pytorch-{{ version }}.tar.gz
  sha256: d8df5047e7e0fcdb9352c33a5cbd0948d5937e05045cb7095ef79511b6fd26b7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - einops >=0.3
    - python >=3.6
    - pytorch >=1.6

test:
  imports:
    - res_mlp_pytorch
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lucidrains/res-mlp-pytorch
  summary: ResMLP - Pytorch
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rpanai
